### ISSUE TITLE
Image server check failed

### ISSUE THREAD

**Issue by AtticusHuang** [derekhe/msfs2020-map-enhancement#296]
When I use Google Maps it goes like in the screenshot, failed to check the image server.

**MSFS version:**
 - msstore
 - MSFS2020 Version 1.29.30.0

**Mod version:**
- 6.2.3.0

**Device ID**
- XTACAE7B4BPHZXWT8CA23W160SDBNXJGTTZXC5614R0Q4W0G1NH0

**Log**
[log.zip](https://github.com/derekhe/msfs2020-map-enhancement/files/10141301/log.zip)

**Screenshots**
![image](https://user-images.githubusercontent.com/97792909/205299510-11dc8977-3e93-4ad2-a6ec-db173223c4c8.png)

**Additional context**
Bing Maps, ArcGIS and Mapbox are available, only Google Maps cannot be used.

**Comment by derekhe** [comment]
Your network access to google is failed, you can check the url is accessable `https://mt.google.com/vt/lyrs=s&x=17&y=14&z=5`

```
2022-12-02 21:09:36.7547|13|ERROR|Microsoft.AspNetCore.Server.Kestrel|Connection id "0HMMKCKOUQPKP", Request id "0HMMKCKOUQPKP:00000002": An unhandled exception was thrown by the application. System.Net.Http.HttpRequestException: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 (mt.google.com:443)
 ---> System.Net.Sockets.SocketException (10060): 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Core.ImageServer.ImageProcessor.RequestImage(String quadKey, MapProvider mapProvider, Boolean fallbackLoad)
   at Core.ImageServer.ImageProcessor.LoadNormalLod(MapProvider mapProvider, String quadKey, Boolean cacheEnabled, HttpContext httpContext)
   at Core.ImageServer.ImageProcessor.ImageHandler(HttpContext context, String path)
   at Microsoft.AspNetCore.Http.RequestDelegateFactory.ExecuteTaskResult[T](Task`1 task, HttpContext httpContext)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Core.ImageServer.ImageServer.ColorCorrectionFilter(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
2022-12-02 21:09:53.5561|0|INFO|MainApp.Views.TroubleShooting|Copying logs to temp 
```

**Comment by AtticusHuang** [comment]
Thanks for your reply. I can access this url in my browser, but this software still can't access it.

**Comment by derekhe** [comment]
I think you may using a proxy to access google in your browser. If this is true, please config the proxy in the setting.

**Comment by AtticusHuang** [comment]
Is the setting in the software or system?

**Comment by derekhe** [comment]
In the software

**Comment by AtticusHuang** [comment]
OK, thanks
