### ISSUE TITLE
Apply hosts change failed

### ISSUE THREAD

**Issue by fsms2020** [derekhe/msfs2020-map-enhancement#369]
**Describe the bug**
the full message I have :
Apply hosts change failed

Unable to patch hosts file. Please try:
Run as administrator.
Turn off your antivirus and restart your computer.
Check if any tools inside your antivirus are protecting your system.
Add this mod into white list.
Please also visit [FAQ page](https://github.com/derekhe/msfs2020-map-enhancement/wiki/FAQ) for more information.
Error detail: Access to the path 'C:\WINDOWS\system32\drivers\etc\hosts' is denied.

**MSFS version:**
 - steam

**Mod version:**
- Mod version 7.1.4 (PRO)

**Device ID**
- QXVCJBEEKDA6RKP039TQQM0TF5A4W0TVAS38PVWVM5D686A5R26G

Please provide me screenshots for the mod and msfs2020 if possible

![image](https://user-images.githubusercontent.com/130523882/231330481-fca18dcd-4105-41e3-91ac-05bdfc322abf.png)

**Additional context**
Hi, I've purchased a full licence (365 days) but no server is accessible.
My norton antivirus is in sleep mode. MSFS2020 MAP Enhancment is running with admin rights. I deactivated the firwall. the "/etc" folder is not in read-only state. hosts file is not corrupted (all lines are commented)
I've used the Free version 7.0.2 before without any problem and with the same config.
I didn't found any solution to use the mod.
Can you solve this problem please ?
Thank you!

**Comment by fsms2020** [comment]
I saw on another topic that you told someone to execute this command:
cd "C:\Program Files\MSFS2020 Map Enhancement\resources\core\release"
core.exe

this is the result I had from my side:
```

[04:50:25 INF] Valid license file: <License>
  <Id>6e128028-f8cb-4281-ab03-a3b86a9bcc04</Id>
  <LicenseAttributes>
    <Attribute name="deviceid">QXVCJBEEKDA6RKP039TQQM0TF5A4W0TVAS38PVWVM5D686A5R26G</Attribute>
  </LicenseAttributes>
  <Type>Standard</Type>
  <Expiration>Thu, 11 Apr 2024 00:07:55 GMT</Expiration>
  <Customer>
    <Name>KARMANI</Name>
    <Email>makarmani2@gmail.com</Email>
  </Customer>
  <Signature>---Commented---</Signature>
</License>
[04:50:25 FTL] Image server unexpected error
System.IO.IOException: Failed to bind to address http://0.0.0.0:42098: address already in use.
 ---> Microsoft.AspNetCore.Connections.AddressInUseException: Une seule utilisation de chaque adresse de socket (protocole/adresse réseau/port) est habituellement autorisée.
 ---> System.Net.Sockets.SocketException (10048): Une seule utilisation de chaque adresse de socket (protocole/adresse réseau/port) est habituellement autorisée.
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportOptions.CreateDefaultBoundListenSocket(EndPoint endpoint)
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.Bind()
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.Bind()
   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportFactory.BindAsync(EndPoint endpoint, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.TransportManager.BindAsync(EndPoint endPoint, ConnectionDelegate connectionDelegate, EndpointConfig endpointConfig, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.<>c__DisplayClass30_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions.BindAsync(AddressBindContext context, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.EndpointsStrategy.BindAsync(AddressBindContext context, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IEnumerable`1 listenOptions, AddressBindContext context, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.BindAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Start(IHost host)
   at core.ImageServer.ImageServer.StartServer() in D:\dev\msfs2020-map-enhancement-dotnet\electron-ui\core\ImageServer\ImageServer.cs:line 38
   at core.Program.Main(String[] args) in D:\dev\msfs2020-map-enhancement-dotnet\electron-ui\core\Program.cs:line 34
```

Hope this could help to find a solution to this problem :/

**Comment by fsms2020** [comment]
Hi, Really strange.
That's the error I have today :

Image server test failed

MS server override is not working
Please try:

Disable any global proxies
Disable any game accelerator
[Create a new hosts file]

Can you help ?

**Comment by derekhe** [comment]
Please have a FAQ here: https://github.com/derekhe/msfs2020-map-enhancement/wiki/FAQ#443-or-42098-port-is-occupied
