### ISSUE TITLE
Timeout error on all servers

### ISSUE THREAD

**Issue by ericviertecbr** [derekhe/msfs2020-map-enhancement#59]
I have this error on all servers since yesterday.

This is rederer.log

[2022-02-13 12:45:10.898] [error] Image server error RequestError: Timeout awaiting 'request' for 15000ms
    at ClientRequest.<anonymous> (app://./js/chunk-vendors.b34d67f6.js:205:18679)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:327:22)
    at ClientRequest.e.emit (app://./js/chunk-vendors.b34d67f6.js:119:1847)
    at Socket.socketErrorListener (_http_client.js:469:9)
    at Socket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
    at b (app://./js/chunk-vendors.b34d67f6.js:49:2049)
[2022-02-13 12:45:14.848] [info]  Stopping mod

**Comment by ericviertecbr** [comment]
started working again!! Thanks
