### ISSUE TITLE
Image Server Access crossed

### ISSUE THREAD

**Issue by syzzori** [derekhe/msfs2020-map-enhancement#76]
**Describe the bug**

The 4.2.0 version Image Server Access is crossed. I tried reinstalling and removing the folder in C:\Users\$USERNAME$\AppData\Roaming\msfs2020-map-enhancement

**MSFS Version**

 - MSFS2020 version: msstore
 - MSFS2020 Version 22

**Logs**

[2022-03-11 23:20:47.378] [info]  Application starting
[2022-03-11 23:20:50.257] [info]  No update version
[2022-03-11 23:20:55.079] [info]  Updating config khm.google.com
[2022-03-11 23:20:55.083] [info]  Updated config
[2022-03-11 23:21:01.190] [info]  Starting mod
[2022-03-11 23:21:01.497] [info]  Start mod result { success: true }
[2022-03-11 23:21:09.503] [info]  Checking image access
[2022-03-11 23:21:09.514] [info]  Checking nginx server
[2022-03-11 23:21:09.545] [info]  Nginx server check result 404
[2022-03-11 23:21:09.545] [info]  Nginx server check passed
[2022-03-11 23:21:12.838] [error] Image server error HTTPError: Response code 500 (INTERNAL SERVER ERROR)
    at de.<anonymous> (app://./js/chunk-vendors.4bc32ce3.js:197:11390)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[2022-03-11 23:21:32.938] [info]  Stopping mod
[2022-03-11 23:21:40.767] [info]  Starting mod
[2022-03-11 23:21:41.120] [info]  Start mod result { success: true }
[2022-03-11 23:21:49.126] [info]  Checking image access
[2022-03-11 23:21:49.129] [info]  Checking nginx server
[2022-03-11 23:21:49.150] [info]  Nginx server check result 404
[2022-03-11 23:21:49.151] [info]  Nginx server check passed
[2022-03-11 23:21:52.539] [error] Image server error HTTPError: Response code 500 (INTERNAL SERVER ERROR)
    at de.<anonymous> (app://./js/chunk-vendors.4bc32ce3.js:197:11390)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[2022-03-11 23:24:03.402] [info]  Updating config Bing Map (Latest)
[2022-03-11 23:24:03.412] [info]  Update server
[2022-03-11 23:24:03.418] [info]  Updated config
[2022-03-11 23:24:05.213] [info]  Stopping mod
[2022-03-11 23:24:13.297] [info]  Starting mod
[2022-03-11 23:24:13.601] [info]  Start mod result { success: true }
[2022-03-11 23:24:21.606] [info]  Checking image access
[2022-03-11 23:24:21.607] [info]  Checking nginx server
[2022-03-11 23:24:21.628] [info]  Nginx server check result 404
[2022-03-11 23:24:21.628] [info]  Nginx server check passed
[2022-03-11 23:24:24.752] [error] Image server error HTTPError: Response code 500 (INTERNAL SERVER ERROR)
    at de.<anonymous> (app://./js/chunk-vendors.4bc32ce3.js:197:11390)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
[2022-03-11 23:24:38.400] [info]  Stopping mod
[2022-03-11 23:24:44.952] [info]  Application starting
[2022-03-11 23:24:48.057] [info]  No update version
[2022-03-11 23:29:53.655] [info]  Starting mod
[2022-03-11 23:29:53.940] [info]  Start mod result { success: true }
[2022-03-11 23:29:54.806] [info]  Stopping mod
[2022-03-11 23:30:01.995] [info]  Checking image access
[2022-03-11 23:30:02.005] [info]  Checking nginx server
[2022-03-11 23:30:06.997] [error] Image server error RequestError: connect ECONNREFUSED 127.0.0.1:39871
    at ClientRequest.<anonymous> (app://./js/chunk-vendors.4bc32ce3.js:205:18707)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:327:22)
    at ClientRequest.e.emit (app://./js/chunk-vendors.4bc32ce3.js:119:1847)
    at Socket.socketErrorListener (_http_client.js:469:9)
    at Socket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
[2022-03-11 23:31:19.606] [info]  Application starting
[2022-03-11 23:31:23.650] [info]  No update version

**Additional info**

I reinstalled the mod at least 15 times still no luck. I tried multiple maps except google like bing maps latest.

**Comment by derekhe** [comment]
Can you give me all the logs mentioned in the "Trouble Shooting" tab?
Also please try disable using the internal cache.

**Comment by syzzori** [comment]
The internal cache is disabled. I'm gonna attach all of the logs.
[main.log](https://github.com/derekhe/msfs2020-map-enhancement/files/8237780/main.log)
[renderer.log](https://github.com/derekhe/msfs2020-map-enhancement/files/8237781/renderer.log)
[image_server.log](https://github.com/derekhe/msfs2020-map-enhancement/files/8237782/image_server.log)
[error.log](https://github.com/derekhe/msfs2020-map-enhancement/files/8237784/error.log)

**Comment by syzzori** [comment]
The same error happens with the new 4.2.1 version.

**Comment by zaelu** [comment]
same for me in 4.21

**Comment by derekhe** [comment]
Sure, let me look at this this weekend.

**Comment by zaelu** [comment]
it is now working again. nothing done on my side.
